blank_issues_enabled: false
contact_links:
  - name: ðŸ“– Documentation
    url: https://into-the-grey.github.io/tr4c3r
    about: Check the documentation for guides and API reference
  - name: ðŸ’¬ Discussions
    url: https://github.com/Into-The-Grey/tr4c3r/discussions
    about: Ask questions and discuss ideas with the community
